// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#ifndef _UI_COMP_HEADER_H
#define _UI_COMP_HEADER_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Header
#define UI_COMP_HEADER_HEADER 0
#define UI_COMP_HEADER_SETTINGBTN 1
#define UI_COMP_HEADER_SETTINGBTN_SETTINGLABLE 2
#define UI_COMP_HEADER_DATE 3
#define _UI_COMP_HEADER_NUM 4
lv_obj_t * ui_Header_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
