// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#include "../ui.h"


// COMPONENT Header

lv_obj_t * ui_Header_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Header;
    cui_Header = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_Header, 30);
    lv_obj_set_width(cui_Header, lv_pct(100));
    lv_obj_clear_flag(cui_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Header, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(cui_Header, lv_color_hex(0x716E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(cui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_settingBtn;
    cui_settingBtn = lv_btn_create(cui_Header);
    lv_obj_set_width(cui_settingBtn, 25);
    lv_obj_set_height(cui_settingBtn, 25);
    lv_obj_set_x(cui_settingBtn, 5);
    lv_obj_set_y(cui_settingBtn, 0);
    lv_obj_set_align(cui_settingBtn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_settingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_settingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_settingLable;
    cui_settingLable = lv_label_create(cui_settingBtn);
    lv_obj_set_width(cui_settingLable, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_settingLable, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_settingLable, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(cui_settingLable, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Date;
    cui_Date = lv_label_create(cui_Header);
    lv_obj_set_width(cui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Date, -5);
    lv_obj_set_y(cui_Date, 0);
    lv_obj_set_align(cui_Date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_Date, "17:03   11-04-2024");
    lv_obj_set_style_text_color(cui_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_HEADER_NUM);
    children[UI_COMP_HEADER_HEADER] = cui_Header;
    children[UI_COMP_HEADER_SETTINGBTN] = cui_settingBtn;
    children[UI_COMP_HEADER_SETTINGBTN_SETTINGLABLE] = cui_settingLable;
    children[UI_COMP_HEADER_DATE] = cui_Date;
    lv_obj_add_event_cb(cui_Header, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Header, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Header_create_hook(cui_Header);
    return cui_Header;
}

