// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#ifndef _QR_CODE_2_8_UI_H
#define _QR_CODE_2_8_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void FadeOn_Animation(lv_obj_t * TargetObject, int delay);
void BGOn_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnOpa_Animation(lv_obj_t * TargetObject, int delay);
void FadeOnUp_Animation(lv_obj_t * TargetObject, int delay);
void FadeOff_Animation(lv_obj_t * TargetObject, int delay);
void Keyboard_Animation(lv_obj_t * TargetObject, int delay);
void BGAnim_Animation(lv_obj_t * TargetObject, int delay);
void Ready_Animation(lv_obj_t * TargetObject, int delay);
void ReadyOpa_Animation(lv_obj_t * TargetObject, int delay);
void RightToLeft_Animation(lv_obj_t * TargetObject, int delay);
void DisplayFlex2_Animation(lv_obj_t * TargetObject, int delay);
void LeftToRight_Animation(lv_obj_t * TargetObject, int delay);
void TopToDown_Animation(lv_obj_t * TargetObject, int delay);
void DownToTop_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_VietQRTM;
extern lv_obj_t * ui_sunRise;
extern lv_obj_t * ui_ContainerInfo;
void ui_event_IDDevice(lv_event_t * e);
extern lv_obj_t * ui_IDDevice;
extern lv_obj_t * ui_CompanyIntro;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_ContainerBtnHome;
extern lv_obj_t * ui_TenAccessPoint;
extern lv_obj_t * ui_BtnStartWiFi;
extern lv_obj_t * ui_LbBtnStartWiFi;
// SCREEN: ui_StaticQR
void ui_StaticQR_screen_init(void);
void ui_event_StaticQR(lv_event_t * e);
extern lv_obj_t * ui_StaticQR;
extern lv_obj_t * ui_Header3;
void ui_event_settingBtn2(lv_event_t * e);
extern lv_obj_t * ui_settingBtn2;
extern lv_obj_t * ui_settingLable2;
extern lv_obj_t * ui_Date2;
extern lv_obj_t * ui_ContainerWiFIStatus;
extern lv_obj_t * ui_WiFiStatus;
extern lv_obj_t * ui_RssiValue;
extern lv_obj_t * ui_ContainerQRStaticInfo;
extern lv_obj_t * ui_ContainerStaticQR;
extern lv_obj_t * ui_SoTaiKhoanStaticQR;
extern lv_obj_t * ui_ChuTaiKhoanStaticQR;
extern lv_obj_t * ui_ImageVietQR;
extern lv_obj_t * ui_Footer;
extern lv_obj_t * ui_TerminalName;
extern lv_obj_t * ui_ImageBanking;
extern lv_obj_t * ui_LinkWebSite;
extern lv_obj_t * ui_PanelContainerDeviceSetting;
extern lv_obj_t * ui_PanelSetting;
extern lv_obj_t * ui_Flex1;
extern lv_obj_t * ui_containerBTN;
void ui_event_PlayAudio(lv_event_t * e);
extern lv_obj_t * ui_PlayAudio;
extern lv_obj_t * ui_LableBtnPlayAudio;
void ui_event_BtnResetAccount(lv_event_t * e);
extern lv_obj_t * ui_BtnResetAccount;
extern lv_obj_t * ui_LableBtnResetAccount;
void ui_event_BtnResetWiFi(lv_event_t * e);
extern lv_obj_t * ui_BtnResetWiFi;
extern lv_obj_t * ui_LableBtnResetWiFi;
extern lv_obj_t * ui_ContainerSlider;
void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_LabelBrightNess;
void ui_event_VolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_VolumeSlider;
extern lv_obj_t * ui_LBVolume;
extern lv_obj_t * ui_PanelDeviceInfo;
extern lv_obj_t * ui_ContainerList;
void ui_event_PanelGesture(lv_event_t * e);
extern lv_obj_t * ui_PanelGesture;
extern lv_obj_t * ui_VietQRTM1;
void ui_event_BTNNext(lv_event_t * e);
extern lv_obj_t * ui_BTNNext;
extern lv_obj_t * ui_LableBTNNext;
void ui_event_BTNBack(lv_event_t * e);
extern lv_obj_t * ui_BTNBack;
extern lv_obj_t * ui_LableBTNBack;
void ui_event_btnGoHome(lv_event_t * e);
extern lv_obj_t * ui_btnGoHome;
extern lv_obj_t * ui_btnGoHomeLable;
// SCREEN: ui_DynamicQR
void ui_DynamicQR_screen_init(void);
void ui_event_DynamicQR(lv_event_t * e);
extern lv_obj_t * ui_DynamicQR;
extern lv_obj_t * ui_LogoVietQR;
extern lv_obj_t * ui_LogoBankUser1;
extern lv_obj_t * ui_ContainerQRD;
extern lv_obj_t * ui_ContainerLogoBank;
extern lv_obj_t * ui_Napas247;
extern lv_obj_t * ui_Footer2;
extern lv_obj_t * ui_ChuTaiKhoanDynamicQR;
extern lv_obj_t * ui_SoTaiKhoanDynamicQR;
extern lv_obj_t * ui_ContainerPayMent;
extern lv_obj_t * ui_AmountTitle;
extern lv_obj_t * ui_AmountValue;
extern lv_obj_t * ui_ImageVietQR1;
// SCREEN: ui_PaymentSuccess_S5
void ui_PaymentSuccess_S5_screen_init(void);
void ui_event_PaymentSuccess_S5(lv_event_t * e);
extern lv_obj_t * ui_PaymentSuccess_S5;
extern lv_obj_t * ui_IMG_Ok_2;
extern lv_obj_t * ui_Label_Succesful;
extern lv_obj_t * ui_ThankYouLB;
extern lv_obj_t * ui_SoTienDaThanhToan;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_vietqr_vn_logo_png);    // assets\VietQR_vn_logo.png
LV_IMG_DECLARE(ui_img_sunrise_png);    // assets\sunrise.png
LV_IMG_DECLARE(ui_img_481985369);    // assets\vietqr-icon-site.png
LV_IMG_DECLARE(ui_img_logo_mb_he_mau_resize_png);    // assets\Logo_MB_he_mau_resize.png
LV_IMG_DECLARE(ui_img_vietqr_notbg_png);    // assets\VietQR_notBg.png
LV_IMG_DECLARE(ui_img_vietqr_h35_png);    // assets\VietQR_h35.png
LV_IMG_DECLARE(ui_img_napas247_png);    // assets\Napas247.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets\ok.png
LV_IMG_DECLARE(ui_img_logo_bidv__h20_png);    // assets\Logo_BIDV._h20.png

LV_FONT_DECLARE(ui_font_arial12);
LV_FONT_DECLARE(ui_font_arial14);
LV_FONT_DECLARE(ui_font_arial16);
LV_FONT_DECLARE(ui_font_arial20);
LV_FONT_DECLARE(ui_font_arialbold14);
LV_FONT_DECLARE(ui_font_arialbold16);
LV_FONT_DECLARE(ui_font_arialbold18);
LV_FONT_DECLARE(ui_font_ariallbi20);
LV_FONT_DECLARE(ui_font_arialli20);
LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
