// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H
#ifdef __cplusplus
extern "C"
{
#endif
    extern lv_obj_t *ui_dynamicQR;
    void homeScreenUnload_cb(lv_event_t *e);
    void ScreenloadStartEvent_cb(lv_event_t *e);
    void play_audio(lv_event_t *e);
    void btnResetAccount_Cb(lv_event_t *e);
    void showModalResetWiFi(lv_event_t *e);
    void BrightnessLV_change_cb(lv_event_t *e);
    void BrightnessLV_save_cb(lv_event_t *e);
    void VolumeLV_change_cb(lv_event_t *e);
    void dynamicQR_unloaded_cb(lv_event_t *e);
    void startTimerToGoScreenStaticQR(lv_event_t *e);
    void ResetTimer(lv_event_t *e);
    void showModalNotifyTranstion(const char *tien);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
