// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HomeScreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_HomeScreen, lv_color_hex(0x6E2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_HomeScreen, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VietQRTM = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_VietQRTM, &ui_img_vietqr_vn_logo_png);
    lv_obj_set_width(ui_VietQRTM, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VietQRTM, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VietQRTM, -3);
    lv_obj_set_y(ui_VietQRTM, -60);
    lv_obj_set_align(ui_VietQRTM, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VietQRTM, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_VietQRTM, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sunRise = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_sunRise, &ui_img_sunrise_png);
    lv_obj_set_width(ui_sunRise, LV_SIZE_CONTENT);   /// 220
    lv_obj_set_height(ui_sunRise, LV_SIZE_CONTENT);    /// 156
    lv_obj_set_x(ui_sunRise, -3);
    lv_obj_set_y(ui_sunRise, -115);
    lv_obj_set_align(ui_sunRise, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sunRise, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sunRise, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerInfo = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_ContainerInfo, 221);
    lv_obj_set_height(ui_ContainerInfo, 66);
    lv_obj_set_x(ui_ContainerInfo, 0);
    lv_obj_set_y(ui_ContainerInfo, 40);
    lv_obj_set_align(ui_ContainerInfo, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ContainerInfo, lv_color_hex(0xF89108), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IDDevice = lv_label_create(ui_ContainerInfo);
    lv_obj_set_width(ui_IDDevice, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IDDevice, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IDDevice, 0);
    lv_obj_set_y(ui_IDDevice, 5);
    lv_obj_set_align(ui_IDDevice, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_IDDevice, "BỨT PHÁ TƯƠNG LAI");
    lv_obj_add_flag(ui_IDDevice, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_IDDevice, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_IDDevice, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_IDDevice, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_IDDevice, &ui_font_arial16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CompanyIntro = lv_label_create(ui_ContainerInfo);
    lv_obj_set_width(ui_CompanyIntro, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CompanyIntro, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CompanyIntro, 0);
    lv_obj_set_y(ui_CompanyIntro, -2);
    lv_obj_set_align(ui_CompanyIntro, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_CompanyIntro, "VIETQR.COM|VIETQR.VN");
    lv_obj_set_style_text_color(ui_CompanyIntro, lv_color_hex(0x0C0CCF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CompanyIntro, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_CompanyIntro, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CompanyIntro, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 4);
    lv_obj_set_y(ui_Label2, -16);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "QR Payment");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Bold_Font, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner2 = lv_spinner_create(ui_HomeScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 45);
    lv_obj_set_height(ui_Spinner2, 45);
    lv_obj_set_x(ui_Spinner2, 0);
    lv_obj_set_y(ui_Spinner2, -8);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ContainerBtnHome = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_ContainerBtnHome);
    lv_obj_set_width(ui_ContainerBtnHome, 230);
    lv_obj_set_height(ui_ContainerBtnHome, 75);
    lv_obj_set_x(ui_ContainerBtnHome, 0);
    lv_obj_set_y(ui_ContainerBtnHome, 115);
    lv_obj_set_align(ui_ContainerBtnHome, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ContainerBtnHome, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ContainerBtnHome, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TenAccessPoint = lv_label_create(ui_ContainerBtnHome);
    lv_obj_set_width(ui_TenAccessPoint, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TenAccessPoint, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TenAccessPoint, 0);
    lv_obj_set_y(ui_TenAccessPoint, 2);
    lv_obj_set_align(ui_TenAccessPoint, LV_ALIGN_TOP_MID);
    lv_obj_set_style_text_font(ui_TenAccessPoint, &ui_font_arial14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnStartWiFi = lv_btn_create(ui_ContainerBtnHome);
    lv_obj_set_width(ui_BtnStartWiFi, 45);
    lv_obj_set_height(ui_BtnStartWiFi, 45);
    lv_obj_set_x(ui_BtnStartWiFi, 0);
    lv_obj_set_y(ui_BtnStartWiFi, 10);
    lv_obj_set_align(ui_BtnStartWiFi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnStartWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnStartWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnStartWiFi, 45, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnStartWiFi, lv_color_hex(0xD61212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnStartWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LbBtnStartWiFi = lv_label_create(ui_BtnStartWiFi);
    lv_obj_set_width(ui_LbBtnStartWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LbBtnStartWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LbBtnStartWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LbBtnStartWiFi, "Wi");
    lv_obj_set_style_text_font(ui_LbBtnStartWiFi, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_IDDevice, ui_event_IDDevice, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);

}
