// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#include "../ui.h"

void ui_PaymentSuccess_S5_screen_init(void)
{
    ui_PaymentSuccess_S5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PaymentSuccess_S5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_PaymentSuccess_S5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_PaymentSuccess_S5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PaymentSuccess_S5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PaymentSuccess_S5, lv_color_hex(0xE81919), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PaymentSuccess_S5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PaymentSuccess_S5, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_IMG_Ok_2 = lv_img_create(ui_PaymentSuccess_S5);
    lv_img_set_src(ui_IMG_Ok_2, &ui_img_ok_png);
    lv_obj_set_width(ui_IMG_Ok_2, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_IMG_Ok_2, LV_SIZE_CONTENT);    /// 124
    lv_obj_set_x(ui_IMG_Ok_2, 0);
    lv_obj_set_y(ui_IMG_Ok_2, 28);
    lv_obj_set_align(ui_IMG_Ok_2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_IMG_Ok_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_IMG_Ok_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_IMG_Ok_2, 62, 62);
    lv_img_set_zoom(ui_IMG_Ok_2, 180);

    ui_Label_Succesful = lv_label_create(ui_PaymentSuccess_S5);
    lv_obj_set_width(ui_Label_Succesful, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Succesful, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Succesful, 0);
    lv_obj_set_y(ui_Label_Succesful, -149);
    lv_obj_set_align(ui_Label_Succesful, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Succesful, "Thanh toán thành công");
    lv_obj_set_style_text_color(ui_Label_Succesful, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Succesful, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label_Succesful, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label_Succesful, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Succesful, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Succesful, &ui_font_arial20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThankYouLB = lv_label_create(ui_PaymentSuccess_S5);
    lv_obj_set_width(ui_ThankYouLB, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThankYouLB, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThankYouLB, 0);
    lv_obj_set_y(ui_ThankYouLB, -16);
    lv_obj_set_align(ui_ThankYouLB, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_ThankYouLB, "Cảm ơn \nQuý khách hàng!");
    lv_obj_set_style_text_color(ui_ThankYouLB, lv_color_hex(0xFA00E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ThankYouLB, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ThankYouLB, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ThankYouLB, &ui_font_ariallbi20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoTienDaThanhToan = lv_label_create(ui_PaymentSuccess_S5);
    lv_obj_set_width(ui_SoTienDaThanhToan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SoTienDaThanhToan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SoTienDaThanhToan, 0);
    lv_obj_set_y(ui_SoTienDaThanhToan, -106);
    lv_obj_set_align(ui_SoTienDaThanhToan, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SoTienDaThanhToan, "100,020,000");
    lv_obj_set_style_text_color(ui_SoTienDaThanhToan, lv_color_hex(0x158900), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoTienDaThanhToan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SoTienDaThanhToan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SoTienDaThanhToan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SoTienDaThanhToan, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoTienDaThanhToan, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_PaymentSuccess_S5, ui_event_PaymentSuccess_S5, LV_EVENT_ALL, NULL);

}
