// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.4
// Project name: QR_code_2_8

#include "../ui.h"

void ui_StaticQR_screen_init(void)
{
    ui_StaticQR = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_StaticQR, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_StaticQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StaticQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header3 = lv_obj_create(ui_StaticQR);
    lv_obj_set_height(ui_Header3, 30);
    lv_obj_set_width(ui_Header3, lv_pct(100));
    lv_obj_set_align(ui_Header3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Header3, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header3, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Header3, lv_color_hex(0x716E6E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingBtn2 = lv_btn_create(ui_Header3);
    lv_obj_set_width(ui_settingBtn2, 30);
    lv_obj_set_height(ui_settingBtn2, 25);
    lv_obj_set_x(ui_settingBtn2, 8);
    lv_obj_set_y(ui_settingBtn2, 0);
    lv_obj_set_align(ui_settingBtn2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_settingBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_settingBtn2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_settingLable2 = lv_label_create(ui_settingBtn2);
    lv_obj_set_width(ui_settingLable2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_settingLable2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_settingLable2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingLable2, "Cfg");
    lv_obj_set_style_text_font(ui_settingLable2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date2 = lv_label_create(ui_Header3);
    lv_obj_set_width(ui_Date2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Date2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Date2, -5);
    lv_obj_set_y(ui_Date2, 0);
    lv_obj_set_align(ui_Date2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Date2, "17:03   11-04-2024");
    lv_obj_set_style_text_color(ui_Date2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerWiFIStatus = lv_obj_create(ui_Header3);
    lv_obj_remove_style_all(ui_ContainerWiFIStatus);
    lv_obj_set_width(ui_ContainerWiFIStatus, 70);
    lv_obj_set_height(ui_ContainerWiFIStatus, 28);
    lv_obj_set_align(ui_ContainerWiFIStatus, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_ContainerWiFIStatus, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_WiFiStatus = lv_label_create(ui_ContainerWiFIStatus);
    lv_obj_set_width(ui_WiFiStatus, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_WiFiStatus, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_WiFiStatus, -28);
    lv_obj_set_y(ui_WiFiStatus, -4);
    lv_obj_set_align(ui_WiFiStatus, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_text_color(ui_WiFiStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WiFiStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WiFiStatus, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RssiValue = lv_label_create(ui_ContainerWiFIStatus);
    lv_obj_set_width(ui_RssiValue, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_RssiValue, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_RssiValue, -24);
    lv_obj_set_y(ui_RssiValue, 8);
    lv_obj_set_align(ui_RssiValue, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_RssiValue, "...");
    lv_obj_set_style_text_color(ui_RssiValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RssiValue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RssiValue, &ui_font_arial12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerQRStaticInfo = lv_obj_create(ui_StaticQR);
    lv_obj_remove_style_all(ui_ContainerQRStaticInfo);
    lv_obj_set_width(ui_ContainerQRStaticInfo, 240);
    lv_obj_set_height(ui_ContainerQRStaticInfo, 250);
    lv_obj_set_x(ui_ContainerQRStaticInfo, 0);
    lv_obj_set_y(ui_ContainerQRStaticInfo, 30);
    lv_obj_set_align(ui_ContainerQRStaticInfo, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerQRStaticInfo, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_ContainerQRStaticInfo, lv_color_hex(0xF31380), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerQRStaticInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerQRStaticInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerQRStaticInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerQRStaticInfo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ContainerQRStaticInfo, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerStaticQR = lv_obj_create(ui_ContainerQRStaticInfo);
    lv_obj_remove_style_all(ui_ContainerStaticQR);
    lv_obj_set_width(ui_ContainerStaticQR, 195);
    lv_obj_set_height(ui_ContainerStaticQR, 195);
    lv_obj_set_x(ui_ContainerStaticQR, 0);
    lv_obj_set_y(ui_ContainerStaticQR, -20);
    lv_obj_set_align(ui_ContainerStaticQR, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerStaticQR, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_ContainerStaticQR, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerStaticQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerStaticQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ContainerStaticQR, lv_color_hex(0xF30F3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ContainerStaticQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ContainerStaticQR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ContainerStaticQR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ContainerStaticQR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ContainerStaticQR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ContainerStaticQR, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SoTaiKhoanStaticQR = lv_label_create(ui_ContainerQRStaticInfo);
    lv_obj_set_width(ui_SoTaiKhoanStaticQR, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_SoTaiKhoanStaticQR, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_SoTaiKhoanStaticQR, 0);
    lv_obj_set_y(ui_SoTaiKhoanStaticQR, -25);
    lv_obj_set_align(ui_SoTaiKhoanStaticQR, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_SoTaiKhoanStaticQR, "Quét mã QR bằng ứng dụng");
    lv_obj_set_style_text_color(ui_SoTaiKhoanStaticQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SoTaiKhoanStaticQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_SoTaiKhoanStaticQR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_SoTaiKhoanStaticQR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SoTaiKhoanStaticQR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SoTaiKhoanStaticQR, &ui_font_arialbold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ChuTaiKhoanStaticQR = lv_label_create(ui_ContainerQRStaticInfo);
    lv_obj_set_width(ui_ChuTaiKhoanStaticQR, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_ChuTaiKhoanStaticQR, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_ChuTaiKhoanStaticQR, 4);
    lv_obj_set_y(ui_ChuTaiKhoanStaticQR, -3);
    lv_obj_set_align(ui_ChuTaiKhoanStaticQR, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_ChuTaiKhoanStaticQR, "VietQR để kích hoạt");
    lv_obj_set_style_text_color(ui_ChuTaiKhoanStaticQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ChuTaiKhoanStaticQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ChuTaiKhoanStaticQR, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ChuTaiKhoanStaticQR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ChuTaiKhoanStaticQR, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ChuTaiKhoanStaticQR, &ui_font_arialbold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageVietQR = lv_img_create(ui_ContainerQRStaticInfo);
    lv_img_set_src(ui_ImageVietQR, &ui_img_481985369);
    lv_obj_set_width(ui_ImageVietQR, LV_SIZE_CONTENT);  /// 25
    lv_obj_set_height(ui_ImageVietQR, LV_SIZE_CONTENT); /// 25
    lv_obj_set_x(ui_ImageVietQR, 0);
    lv_obj_set_y(ui_ImageVietQR, -20);
    lv_obj_set_align(ui_ImageVietQR, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageVietQR, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_ImageVietQR, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_ImageVietQR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImageVietQR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Footer = lv_obj_create(ui_StaticQR);
    lv_obj_remove_style_all(ui_Footer);
    lv_obj_set_width(ui_Footer, 240);
    lv_obj_set_height(ui_Footer, 40);
    lv_obj_set_x(ui_Footer, -1);
    lv_obj_set_y(ui_Footer, -1);
    lv_obj_set_align(ui_Footer, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Footer, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_Footer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Footer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TerminalName = lv_label_create(ui_Footer);
    lv_obj_set_width(ui_TerminalName, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_TerminalName, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_TerminalName, 0);
    lv_obj_set_y(ui_TerminalName, -11);
    lv_obj_set_align(ui_TerminalName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TerminalName, "----------------------");
    lv_obj_add_flag(ui_TerminalName, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE); /// Flags
    lv_obj_set_style_text_color(ui_TerminalName, lv_color_hex(0x282EFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TerminalName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TerminalName, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TerminalName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TerminalName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TerminalName, &ui_font_arialbold16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageBanking = lv_img_create(ui_Footer);
    lv_img_set_src(ui_ImageBanking, &ui_img_logo_mb_he_mau_resize_png);
    lv_obj_set_width(ui_ImageBanking, LV_SIZE_CONTENT);  /// 100
    lv_obj_set_height(ui_ImageBanking, LV_SIZE_CONTENT); /// 45
    lv_obj_set_align(ui_ImageBanking, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ImageBanking, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST); /// Flags
    lv_obj_clear_flag(ui_ImageBanking, LV_OBJ_FLAG_SCROLLABLE);                     /// Flags

    ui_LinkWebSite = lv_label_create(ui_Footer);
    lv_obj_set_width(ui_LinkWebSite, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LinkWebSite, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LinkWebSite, 5);
    lv_obj_set_y(ui_LinkWebSite, -3);
    lv_obj_set_align(ui_LinkWebSite, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_LinkWebSite, "vietqr.vn|vietqr.com");
    lv_obj_set_style_text_color(ui_LinkWebSite, lv_color_hex(0x023466), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LinkWebSite, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LinkWebSite, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LinkWebSite, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LinkWebSite, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LinkWebSite, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelContainerDeviceSetting = lv_obj_create(ui_StaticQR);
    lv_obj_set_width(ui_PanelContainerDeviceSetting, 240);
    lv_obj_set_height(ui_PanelContainerDeviceSetting, 320);
    lv_obj_set_align(ui_PanelContainerDeviceSetting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelContainerDeviceSetting, LV_OBJ_FLAG_HIDDEN);                                    /// Flags
    lv_obj_clear_flag(ui_PanelContainerDeviceSetting, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_PanelContainerDeviceSetting, lv_color_hex(0x413E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelContainerDeviceSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelContainerDeviceSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelContainerDeviceSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSetting = lv_obj_create(ui_PanelContainerDeviceSetting);
    lv_obj_set_width(ui_PanelSetting, 240);
    lv_obj_set_height(ui_PanelSetting, 256);
    lv_obj_set_x(ui_PanelSetting, -240);
    lv_obj_set_y(ui_PanelSetting, -10);
    lv_obj_set_align(ui_PanelSetting, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_PanelSetting, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSetting, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSetting, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_PanelSetting, lv_color_hex(0x413E3E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSetting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Flex1 = lv_obj_create(ui_PanelSetting);
    lv_obj_remove_style_all(ui_Flex1);
    lv_obj_set_width(ui_Flex1, 240);
    lv_obj_set_height(ui_Flex1, 180);
    lv_obj_set_align(ui_Flex1, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Flex1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Flex1, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Flex1, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_containerBTN = lv_obj_create(ui_Flex1);
    lv_obj_remove_style_all(ui_containerBTN);
    lv_obj_set_width(ui_containerBTN, 85);
    lv_obj_set_height(ui_containerBTN, 160);
    lv_obj_set_x(ui_containerBTN, 51);
    lv_obj_set_y(ui_containerBTN, 34);
    lv_obj_set_flex_flow(ui_containerBTN, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_containerBTN, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_containerBTN, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_containerBTN, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_containerBTN, lv_color_hex(0xFAF4F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_containerBTN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_containerBTN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_containerBTN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_containerBTN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_containerBTN, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlayAudio = lv_btn_create(ui_containerBTN);
    lv_obj_set_width(ui_PlayAudio, 85);
    lv_obj_set_height(ui_PlayAudio, 45);
    lv_obj_set_align(ui_PlayAudio, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_PlayAudio, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_PlayAudio, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_PlayAudio, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableBtnPlayAudio = lv_label_create(ui_PlayAudio);
    lv_obj_set_width(ui_LableBtnPlayAudio, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LableBtnPlayAudio, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LableBtnPlayAudio, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableBtnPlayAudio, "run");
    lv_obj_set_style_text_letter_space(ui_LableBtnPlayAudio, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LableBtnPlayAudio, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableBtnPlayAudio, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnResetAccount = lv_btn_create(ui_containerBTN);
    lv_obj_set_width(ui_BtnResetAccount, 85);
    lv_obj_set_height(ui_BtnResetAccount, 45);
    lv_obj_set_align(ui_BtnResetAccount, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BtnResetAccount, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_BtnResetAccount, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_BtnResetAccount, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnResetAccount, lv_color_hex(0x841B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnResetAccount, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableBtnResetAccount = lv_label_create(ui_BtnResetAccount);
    lv_obj_set_width(ui_LableBtnResetAccount, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LableBtnResetAccount, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LableBtnResetAccount, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableBtnResetAccount, "run");
    lv_obj_set_style_text_letter_space(ui_LableBtnResetAccount, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LableBtnResetAccount, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableBtnResetAccount, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnResetWiFi = lv_btn_create(ui_containerBTN);
    lv_obj_set_width(ui_BtnResetWiFi, 85);
    lv_obj_set_height(ui_BtnResetWiFi, 45);
    lv_obj_set_align(ui_BtnResetWiFi, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BtnResetWiFi, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_BtnResetWiFi, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_BtnResetWiFi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnResetWiFi, lv_color_hex(0x14962E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnResetWiFi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LableBtnResetWiFi = lv_label_create(ui_BtnResetWiFi);
    lv_obj_set_width(ui_LableBtnResetWiFi, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LableBtnResetWiFi, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LableBtnResetWiFi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableBtnResetWiFi, "run");
    lv_obj_set_style_text_letter_space(ui_LableBtnResetWiFi, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LableBtnResetWiFi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LableBtnResetWiFi, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerSlider = lv_obj_create(ui_Flex1);
    lv_obj_remove_style_all(ui_ContainerSlider);
    lv_obj_set_width(ui_ContainerSlider, 118);
    lv_obj_set_height(ui_ContainerSlider, 160);
    lv_obj_set_align(ui_ContainerSlider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerSlider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerSlider, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerSlider, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_BrightnessSlider = lv_slider_create(ui_ContainerSlider);
    lv_slider_set_mode(ui_BrightnessSlider, LV_SLIDER_MODE_SYMMETRICAL);
    lv_slider_set_value(ui_BrightnessSlider, 80, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 52);
    lv_obj_set_height(ui_BrightnessSlider, 155);
    lv_obj_set_x(ui_BrightnessSlider, -9);
    lv_obj_set_y(ui_BrightnessSlider, 70);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_BrightnessSlider, LV_OBJ_FLAG_CLICKABLE); /// Flags
    lv_obj_set_style_radius(ui_BrightnessSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xB1B1BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrightnessSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xF2F1F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LabelBrightNess = lv_label_create(ui_BrightnessSlider);
    lv_obj_set_width(ui_LabelBrightNess, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LabelBrightNess, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LabelBrightNess, 0);
    lv_obj_set_y(ui_LabelBrightNess, -5);
    lv_obj_set_align(ui_LabelBrightNess, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelBrightNess, "BN");
    lv_obj_set_style_text_color(ui_LabelBrightNess, lv_color_hex(0x4A4949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelBrightNess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LabelBrightNess, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LabelBrightNess, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelBrightNess, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VolumeSlider = lv_slider_create(ui_ContainerSlider);
    lv_slider_set_value(ui_VolumeSlider, 50, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_VolumeSlider) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_VolumeSlider, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_VolumeSlider, 52);
    lv_obj_set_height(ui_VolumeSlider, 155);
    lv_obj_set_x(ui_VolumeSlider, 0);
    lv_obj_set_y(ui_VolumeSlider, -5);
    lv_obj_set_align(ui_VolumeSlider, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_VolumeSlider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xB1B1BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VolumeSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xF2F1F1), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xBD6262), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_LBVolume = lv_label_create(ui_VolumeSlider);
    lv_obj_set_width(ui_LBVolume, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LBVolume, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_LBVolume, 0);
    lv_obj_set_y(ui_LBVolume, -5);
    lv_obj_set_align(ui_LBVolume, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LBVolume, "VL");
    lv_obj_set_style_text_color(ui_LBVolume, lv_color_hex(0x4A4949), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LBVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_LBVolume, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_LBVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LBVolume, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelDeviceInfo = lv_obj_create(ui_PanelContainerDeviceSetting);
    lv_obj_set_width(ui_PanelDeviceInfo, 240);
    lv_obj_set_height(ui_PanelDeviceInfo, 255);
    lv_obj_set_x(ui_PanelDeviceInfo, 0);
    lv_obj_set_y(ui_PanelDeviceInfo, -10);
    lv_obj_set_align(ui_PanelDeviceInfo, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelDeviceInfo, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_PanelDeviceInfo, lv_color_hex(0xCCC8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelDeviceInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelDeviceInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelDeviceInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelDeviceInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelDeviceInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelDeviceInfo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerList = lv_obj_create(ui_PanelDeviceInfo);
    lv_obj_remove_style_all(ui_ContainerList);
    lv_obj_set_width(ui_ContainerList, 225);
    lv_obj_set_height(ui_ContainerList, 180);
    lv_obj_set_x(ui_ContainerList, 0);
    lv_obj_set_y(ui_ContainerList, 20);
    lv_obj_set_align(ui_ContainerList, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ContainerList, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_ContainerList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ContainerList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ContainerList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelGesture = lv_obj_create(ui_PanelContainerDeviceSetting);
    lv_obj_set_width(ui_PanelGesture, 240);
    lv_obj_set_height(ui_PanelGesture, 60);
    lv_obj_set_x(ui_PanelGesture, 0);
    lv_obj_set_y(ui_PanelGesture, 10);
    lv_obj_set_align(ui_PanelGesture, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_PanelGesture, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_PanelGesture, lv_color_hex(0xCCC8C8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelGesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PanelGesture, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PanelGesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelGesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_PanelGesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_PanelGesture, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VietQRTM1 = lv_img_create(ui_PanelGesture);
    lv_img_set_src(ui_VietQRTM1, &ui_img_vietqr_notbg_png);
    lv_obj_set_width(ui_VietQRTM1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_VietQRTM1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_VietQRTM1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_VietQRTM1, LV_OBJ_FLAG_ADV_HITTEST);  /// Flags
    lv_obj_clear_flag(ui_VietQRTM1, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_img_set_zoom(ui_VietQRTM1, 190);

    ui_BTNNext = lv_obj_create(ui_PanelGesture);
    lv_obj_set_width(ui_BTNNext, 40);
    lv_obj_set_height(ui_BTNNext, 60);
    lv_obj_set_x(ui_BTNNext, 5);
    lv_obj_set_y(ui_BTNNext, 0);
    lv_obj_set_align(ui_BTNNext, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_radius(ui_BTNNext, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTNNext, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTNNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNNext, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNNext, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNNext, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNNext, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LableBTNNext = lv_label_create(ui_BTNNext);
    lv_obj_set_width(ui_LableBTNNext, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LableBTNNext, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LableBTNNext, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableBTNNext, ">");
    lv_obj_set_style_text_color(ui_LableBTNNext, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableBTNNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTNBack = lv_obj_create(ui_PanelGesture);
    lv_obj_set_width(ui_BTNBack, 40);
    lv_obj_set_height(ui_BTNBack, 60);
    lv_obj_set_x(ui_BTNBack, -5);
    lv_obj_set_y(ui_BTNBack, 0);
    lv_obj_set_align(ui_BTNBack, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTNBack, LV_OBJ_FLAG_HIDDEN); /// Flags
    lv_obj_set_style_radius(ui_BTNBack, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTNBack, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTNBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BTNBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BTNBack, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BTNBack, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BTNBack, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BTNBack, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LableBTNBack = lv_label_create(ui_BTNBack);
    lv_obj_set_width(ui_LableBTNBack, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_LableBTNBack, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_LableBTNBack, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LableBTNBack, "<");
    lv_obj_set_style_text_color(ui_LableBTNBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LableBTNBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGoHome = lv_btn_create(ui_PanelContainerDeviceSetting);
    lv_obj_set_width(ui_btnGoHome, 30);
    lv_obj_set_height(ui_btnGoHome, 25);
    lv_obj_set_x(ui_btnGoHome, 5);
    lv_obj_set_y(ui_btnGoHome, -8);
    lv_obj_set_align(ui_btnGoHome, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_btnGoHome, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_btnGoHome, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_btnGoHome, lv_color_hex(0x29AC40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnGoHome, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnGoHomeLable = lv_label_create(ui_btnGoHome);
    lv_obj_set_width(ui_btnGoHomeLable, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_btnGoHomeLable, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_btnGoHomeLable, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btnGoHomeLable, "Cfg");
    lv_obj_set_style_text_font(ui_btnGoHomeLable, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settingBtn2, ui_event_settingBtn2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PlayAudio, ui_event_PlayAudio, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnResetAccount, ui_event_BtnResetAccount, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnResetWiFi, ui_event_BtnResetWiFi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeSlider, ui_event_VolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNNext, ui_event_BTNNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTNBack, ui_event_BTNBack, LV_EVENT_ALL, NULL);
    // lv_obj_add_event_cb(ui_PanelGesture, ui_event_PanelGesture, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnGoHome, ui_event_btnGoHome, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StaticQR, ui_event_StaticQR, LV_EVENT_ALL, NULL);
}
